name: David Aaron Pierce
permalink: /blog/:year/:month/:day/:title.html
collections:
  - projects
markdown: kramdown
kramdown:
  math_engine: mathjax
highlighter: rouge
plugins_dir:
  - jekyll-sitemap
  - jemoji
